# Workflow: SMPL_E2E_MLOPS_GCP_Manual_Docker_Build
# Prefix Meaning: SMPL_E2E_MLOPS_GCP = Simple End-to-End MLOps on Google Cloud
# This workflow builds a Docker image, tags it with a timestamp, uploads it as an artifact, and creates a Git tag.

name: Manual Docker Build

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      IMAGE_NAME:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate timestamp tag
        run: echo "TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
          docker build -f devops/dockerBuild/Dockerfile -t $IMAGE_NAME:${TAG} .

      - name: Save image as artifact
        run: docker save ${{ secrets.IMAGE_NAME }}:${TAG} | gzip > ${{ secrets.IMAGE_NAME }}-${TAG}.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ env.TAG }}
          path: ${{ secrets.IMAGE_NAME }}-${{ env.TAG }}.tar.gz

      - name: Tag the codebase
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.TAG }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.TAG }}
