
name: GCP Docker Build & Push

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate timestamp
        run: echo "TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # Inject credentials.json securely
      - name: Write GCP credentials to file
        run: echo "${{ secrets.SMPL_E2E_MLOPS_GCP_CREDENTIALS }}" > credentials.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SMPL_E2E_MLOPS_GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev

      - name: Ensure Artifact Registry exists
        run: |
          if ! gcloud artifacts repositories describe smpl-e2e-mlops-gcp --location=${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }} --project=${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }} >/dev/null 2>&1; then
            gcloud artifacts repositories create smpl-e2e-mlops-gcp \
              --repository-format=docker \
              --location=${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }} \
              --project=${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }} || echo "⚠️ Could not create repository."
          fi

      - name: Build Docker image
        run: docker build -f devops/dockerBuild/Dockerfile -t ${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${TAG} .

      - name: Tag image for Artifact Registry
        run: |
          docker tag ${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${TAG} \
          ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${TAG}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${TAG}

      # Cleanup credentials file
      - name: Cleanup credentials file
        run: rm credentials.json
