
name: GCP Deploy Latest to Cloud Run

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      service_name:
        required: false
        type: string
    secrets:
      PROJECT_ID:
        required: true
      REGION:
        required: true
      IMAGE_NAME:
        required: true
      SERVICE_NAME:
        required: true
      SERVICE_ACCOUNT_EMAIL:
        required: true

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set run/region ${{ secrets.REGION }}

      - name: Set environment variables for app
        run: |
          echo "CREDENTIALS_SOURCE=gcs" >> $GITHUB_ENV
          echo "GCS_BUCKET_NAME=e2e-ml-ops" >> $GITHUB_ENV

      - name: Get latest image tag
        id: get-tag
        run: |
          IMAGE_NAME="${{ inputs.image_name || secrets.IMAGE_NAME }}"
          LATEST_TAG=$(gcloud artifacts docker tags list ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/smpl-e2e-mlops-gcp/$IMAGE_NAME \
            --sort-by=~CREATE_TIME --limit=1 --format="value(TAG)")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ inputs.image_name || secrets.IMAGE_NAME }}:${LATEST_TAG}"
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image $IMAGE \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} \
            --update-env-vars CREDENTIALS_SOURCE=gcs,GCS_BUCKET_NAME=e2e-ml-ops
