
name: GCP Deploy Latest to Cloud Run

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      service_name:
        required: false
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true
      PROJECT_ID:
        required: true
      REGION:
        required: true
      IMAGE_NAME:
        required: true
      SERVICE_NAME:
        required: true

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get latest image tag
        id: get-tag
        run: |
          PROJECT_ID="${{ secrets.PROJECT_ID }}"
          REGION="${{ secrets.REGION }}"
          REPO_NAME="smpl-e2e-mlops-gcp"
          IMAGE_NAME="${{ inputs.image_name || secrets.IMAGE_NAME }}"

          echo "Fetching latest tag for $IMAGE_NAME..."
          LATEST_TAG=$(gcloud artifacts docker tags list $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME \
            --sort-by=~CREATE_TIME \
            --limit=1 \
            --format="value(TAG)")

          if [ -z "$LATEST_TAG" ]; then
            echo "âŒ No image tags found. Exiting."
            exit 1
          fi

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          PROJECT_ID="${{ secrets.PROJECT_ID }}"
          REGION="${{ secrets.REGION }}"
          SERVICE_NAME="${{ inputs.service_name || secrets.SERVICE_NAME }}"
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/smpl-e2e-mlops-gcp/${{ inputs.image_name || secrets.IMAGE_NAME }}:${LATEST_TAG}"

          echo "Deploying latest image: $IMAGE"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --timeout=900s
