
name: GCP Deploy Latest to Cloud Run

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SMPL_E2E_MLOPS_SERVICE_ACCOUNT_EMAIL }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}

      - name: Set environment variables for app
        run: |
          echo "CREDENTIALS_SOURCE=gcs" >> $GITHUB_ENV
          echo "GCS_BUCKET_NAME=e2e-ml-ops" >> $GITHUB_ENV

      - name: Get latest image tag
        id: get-tag
        run: |
          IMAGE_NAME="${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}"
          LATEST_TAG=$(gcloud artifacts docker tags list ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/$IMAGE_NAME \
            --sort-by=~CREATE_TIME --limit=1 --format="value(TAG)")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${LATEST_TAG}"
          gcloud run deploy ${{ secrets.SMPL_E2E_MLOPS_SERVICE_NAME }} \
            --image $IMAGE \
            --region ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ secrets.SMPL_E2E_MLOPS_SERVICE_ACCOUNT_EMAIL }} \
            --update-env-vars CREDENTIALS_SOURCE=gcs,GCS_BUCKET_NAME=e2e-ml-ops
