
name: GCP Deploy Latest to Cloud Run

on:
  workflow_call:

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SMPL_E2E_MLOPS_GCP_CREDENTIALS }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}

      - name: Get latest image tag
        id: get-tag
        run: |
          IMAGE_NAME="${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}"
          LATEST_TAG=$(gcloud artifacts docker tags list \
            ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/$IMAGE_NAME \
            --sort-by=~CREATE_TIME --limit=1 --format="value(TAG)")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev/${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.SMPL_E2E_MLOPS_IMAGE_NAME }}:${LATEST_TAG}"
          gcloud run deploy ${{ secrets.SMPL_E2E_MLOPS_SERVICE_NAME }} \
            --image $IMAGE \
            --region ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ secrets.SMPL_E2E_MLOPS_SERVICE_ACCOUNT_EMAIL }}
