name: GCP Build Push Deploy

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: false
        type: string
      project_id:
        required: false
        type: string
      region:
        required: false
        type: string
      service_name:
        required: false
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate timestamp and image name
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          IMAGE_NAME="${{ inputs.image_name || 'simple-e2e-mlops-on-gcp' }}"
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SMPL_E2E_MLOPS_GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}-docker.pkg.dev

      - name: Ensure Artifact Registry exists
        run: |
          PROJECT_ID="${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}"
          REGION="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}"
          REPO_NAME="smpl-e2e-mlops-gcp"
          if ! gcloud artifacts repositories describe $REPO_NAME --location=$REGION --project=$PROJECT_ID >/dev/null 2>&1; then
            gcloud artifacts repositories create $REPO_NAME \
              --repository-format=docker \
              --location=$REGION \
              --project=$PROJECT_ID || echo "⚠️ Could not create repository."
          fi

      - name: Build Docker image
        run: docker build -f devops/dockerBuild/Dockerfile -t $IMAGE_NAME:$TIMESTAMP .

      - name: Tag image for Artifact Registry
        run: |
          PROJECT_ID="${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}"
          REGION="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}"
          REPO_NAME="smpl-e2e-mlops-gcp"
          docker tag $IMAGE_NAME:$TIMESTAMP $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$TIMESTAMP

      - name: Push image to Artifact Registry
        run: |
          PROJECT_ID="${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}"
          REGION="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}"
          REPO_NAME="smpl-e2e-mlops-gcp"
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$TIMESTAMP

      - name: Deploy to Cloud Run
        run: |
          PROJECT_ID="${{ secrets.SMPL_E2E_MLOPS_GCP_PROJECT_ID }}"
          REGION="${{ secrets.SMPL_E2E_MLOPS_GCP_REGION }}"
          SERVICE_NAME="smpl-e2e-mlops-gcp-service"
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/smpl-e2e-mlops-gcp/$IMAGE_NAME:$TIMESTAMP"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --timeout=900s

      - name: Tag the codebase
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TIMESTAMP
