
name: GCP Docker Build & Push

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      PROJECT_ID:
        required: true
      REGION:
        required: true
      IMAGE_NAME:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Google Cloud GCP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate timestamp
        run: echo "TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Ensure Artifact Registry exists
        run: |
          if ! gcloud artifacts repositories describe smpl-e2e-mlops-gcp --location=${{ secrets.REGION }} --project=${{ secrets.PROJECT_ID }} >/dev/null 2>&1; then
            gcloud artifacts repositories create smpl-e2e-mlops-gcp \
              --repository-format=docker \
              --location=${{ secrets.REGION }} \
              --project=${{ secrets.PROJECT_ID }} || echo "⚠️ Could not create repository."
          fi

      - name: Build Docker image
        run: docker build -f devops/dockerBuild/Dockerfile -t ${{ secrets.IMAGE_NAME }}:${TAG} .

      - name: Tag image for Artifact Registry
        run: |
          docker tag ${{ secrets.IMAGE_NAME }}:${TAG} \
          ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.IMAGE_NAME }}:${TAG}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/smpl-e2e-mlops-gcp/${{ secrets.IMAGE_NAME }}:${TAG}
